# Server Port (IMPORTANT for Render)
server.port=${PORT:8083}

# MongoDB (use environment variable)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/event_db}

# Application Name
spring.application.name=event-service

# Logging
logging.level.org.springframework=INFO