# Server Port
server.port=8083

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/event_db

# Application Name
spring.application.name=event-service

# Logging
logging.level.org.springframework=INFO