# Server Port
server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/faculty_db

# Application Name (optional but good for microservices)
spring.application.name=faculty-service
