spring.application.name=Student_Event_Registration_Management_System
server.port=${PORT}
# This tells Spring to use the Render variable, or default to localhost if missing
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/test}